feat(devices): added total pages to devices response
infinimesh/proto pull request #75
Opened 2024-02-01 19:05 UTC by vladimirnikolic509

2024-02-02 13:20 UTC, gorobot-nz approved these changes

2024-02-02 19:12 UTC, slntopp requested changes

2024-02-02 19:12 UTC, slntopp commented on node/devices/devices.proto
> +  int64 totalPages = 2;
Better to use "total" and provide the total number of the devices.

- Amount of devices per page is dynamic
- Should show the total number at the top of the page in the front-end

```suggestion
  int64 total = 2;
```

Or

```suggestion
  int64 count = 2;
```

2024-02-05 07:47 UTC, vladimirnikolic509 commented on node/devices/devices.proto
> +  int64 totalPages = 2;
Done

2024-02-05 15:12 UTC, slntopp approved these changes

2024-02-05 16:08 UTC, merged